version: 1

model:
  level:
    0:
      provider: openai
      model: gpt-6-astra
      options:
        reasoning_effort: xhigh

    1:
      provider: openai
      model: gpt-5.6-sol
      options:
        reasoning_effort: high

    2:
      provider: openai
      model: gpt-5.6-sol
      options:
        reasoning_effort: medium

    3:
      provider: openai
      model: gpt-5.6-luna
      options:
        reasoning_effort: xhigh
